close opened tab before tests execution
gemini-testing/hermione-tabs-closer pull request #1
Opened 2018-02-14 21:54 UTC by rostik404

2018-02-15 08:52 UTC, sipayRT requested changes
есть вопросы

2018-02-15 08:52 UTC, sipayRT commented on README.md
> +### Hermione Usage
usage с маленькой буквы

2018-02-15 08:52 UTC, sipayRT commented on config/index.js
> +                    throw new Error(`"browsersToExclude" option must be string, but got ${typeof v}`);
must be an array of strings

2018-02-15 08:52 UTC, sipayRT commented on index.js
> +            .then(tabIds => {
скобки забыл для аргумента

2018-02-15 08:52 UTC, sipayRT commented on index.js
> +                return tabIds.reduce((browser, id, ind) => {
ну уже бы дописал до `index`

2018-02-15 08:52 UTC, sipayRT commented on index.js
> +            return (pluginConfig.browsersToExclude || []).includes(data.browser)
`|| []` здесь не нужен - ты в конфиг-парсере указал дефолтное значение

2018-02-15 08:52 UTC, sipayRT commented on test/index.js
> +    it('it should close all opend tabs except first tab', () => {
openEd

2018-02-15 08:52 UTC, sipayRT commented on index.js
> +                : closeTabs.apply(this.browser);
почему не сделать эту функцию командой браузера? тут бы просто позвал `this.browser.closeTabs()`

2018-02-15 08:52 UTC, sipayRT commented on test/index.js
> +    it('it should close all opend tabs except first tab', () => {
в описании теста не нужен "it " а начале строки

2018-02-15 08:52 UTC, sipayRT commented on index.js
> +                    const nextTabId = tabIds[ind + 1];
мы же вроде должны последнюю вкладку оставить, а не первую

2018-02-15 08:52 UTC, sipayRT commented on test/index.js
> +    it('it should not close tabs for excluded browsers', () => {
лишний "it "

2018-02-15 08:52 UTC, sipayRT commented on test/index.js
> +        tabsCloser(hermione);
если переименовать в `plugin`, то будет понятней

2018-02-15 08:52 UTC, sipayRT commented on test/index.js
> +                assert.match(res, {some: 'bro'});
так если ты здесь все равно буешь закрывать табы, то ты ведь в любом случае в res получишь инстанс браузера

2018-02-15 16:41 UTC, rostik404 commented on index.js
> +                    const nextTabId = tabIds[ind + 1];
обсудили голосом - так работает `close`: закрывает текущую вкладку и переходит на ту, которую ему передали аргументом. Так что здесь все ок

2018-02-16 07:28 UTC, DudaGod commented on README.md
>  Plugin for hermione to close opened tabs from previous tests in a browser
Я бы тут чуть подробнее описал, что когда мы запускаем пачку тестов в одной и той же сессии, то начинают накапливаться вкладки из-за чего браузер может деградировать. Для этого перед выполнением каждого теста необходимо закрывать такие вкладки.

2018-02-16 07:28 UTC, DudaGod commented on README.md
> +* **browsersToExclude** (optional) `Array` - array of browsers to exclude from closing tabs
А если нужно будет не только браузеры эксклюдить? А например не применять этот плагин для таких то файлов =)
Я к тому, что я бы эту опцию сделал более generic:
```
exclude: {
  browsers: ['ie11']
}
```

2018-02-16 07:28 UTC, DudaGod commented on index.js
> +                : closeTabs.apply(this.browser);
а почему ты туда просто браузер не передашь?
```js
closeTabs(this.browser);
```

2018-02-16 07:28 UTC, DudaGod commented on index.js
> +                    return this.close(nextTabId);
я бы так написал:
```js
return (ind === tabIds.length - 1)
  ? browser
  : this.close(tabIds[ind + 1]);
```

Итак понятно, что `tabIds[ind + 1]` - это следующий табик

2018-02-16 07:28 UTC, DudaGod commented on test/index.js
> +    it('should close all opened tabs except first tab', () => {
тут `except last tab` должен быть

2018-02-16 07:28 UTC, DudaGod commented on test/index.js
> +        };
чего хелпер не написал типа `mkData`? Тогда же тест будет менее мясным

2018-02-16 07:28 UTC, DudaGod commented on test/index.js
> +    });
у тебя нет теста на то, что если вкладка одна, то никакие вкладки закрываться не должны

2018-02-16 07:28 UTC, DudaGod commented on test/index.js
> +        };
я бы для этого тоже какой то `mkBrowser` написал бы

2018-02-16 08:20 UTC, DudaGod commented on index.js
> +                return Promise.reduce(tabIds, (browser, id, ind) => {
`Promise.reduce` нужно юзать когда тебе нужно какой то результат накапливать, а ты тут ничего не накапливаешь, а только выполняешь последовательно. Чтобы никого не путать давай явно юзнем `Promise.mapSeries`:

```js
return Promise.mapSeries(tabIds, (id, ind) => {...});
```

А браузер будет доступен из замыкания.

2018-02-16 09:06 UTC, rostik404 commented on test/index.js
> +    });
Логика про то, что одна вкладка не закрывается, покрывается этим тестом. Случай с одной вкладкой является частным случаем, когда у нас есть несколько вкладок и нужно закрыть все, кроме последней.

2018-02-16 10:45 UTC, DudaGod commented on test/index.js
> +    });
Нет, этим тестом ты покрыл, что браузер заэкслюдился и он не пошел вкладки закрывать. Если браузер исключать не нужно и в нем одна вкладка, то `close` вообще вызываться не должен.

2018-02-16 11:21 UTC, rostik404 commented on test/index.js
> +        };
Не получится, я здесь в замыкание сохраняю функцию, с которой позовется `beforeEach` и дальше в тесте ее использую

2018-02-16 11:26 UTC, rostik404 commented on test/index.js
> +    });
Да, я перепутал, эта логика покрывается в первом тесте  -`should close all opened tabs except last tab`

2018-02-16 11:40 UTC, DudaGod commented on .npmignore
> +test
а чего ты не заигнорил все конфигурационные файлы начинающиеся с точки? - `.*`

2018-02-16 12:00 UTC, DudaGod approved these changes
/ok

2018-02-16 12:00 UTC, DudaGod commented on README.md
> +* **browsers** (optional) `Regex` - browsers in which tabs should be closed
ты букву `p` потерял в слове `regex`

2018-02-16 12:00 UTC, DudaGod commented on index.js
> +        return pluginConfig.browsers.test(browser) && browserConf.testsPerSession !== 1;
я бы указал `browserConf.testsPerSession <= 1`

2018-02-16 12:25 UTC, DudaGod commented on README.md
> +### Hermione usage
кстати вот этот заголовок лишний итак понятно, что ты его только для гермионы юзаешь

2018-02-16 14:15 UTC, rostik404 commented on README.md
> +### Hermione usage
Ну тут имеется в виду раздел конкретно про подключение в гермионе

2018-02-16 14:32 UTC, sipayRT approved these changes
можно написать тест на кейс, когда мы указали `testsPerSession: 10` ( но он примитивный)
в остальном 🔥

2018-02-16 14:32 UTC, sipayRT commented on README.md
> +* **browsers** (optional) `Regex` - browsers in which tabs should be closed
RegExp

2018-02-16 14:32 UTC, sipayRT commented on index.js
> +    function shouldClose(browser) {
browserId

2018-02-16 21:11 UTC, DudaGod commented on README.md
> +### Hermione usage
Как будто ты его еще к чему то можешь подключить =)

Я бы его выгасил, ты скорей всего взял его из `html-reporter` в котором описано как подключить к `gemini` или к `hermione`. Там такой заголовок валиден, а тут он излишний имхо.

2018-02-17 17:21 UTC, merged